package tui_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	tea "charm.land/bubbletea/v2"
	"github.com/charmbracelet/x/ansi"

	"jig/internal/engine"
	domainreview "jig/internal/review"
	"jig/internal/runner"
	"jig/internal/step"
	"jig/internal/tui"
	"jig/internal/tui/monitor"
	"jig/internal/tui/selector"
)

// TestGoldenPathProofFrames writes the six SCRIPT.md reference frames as
// stripped text proofs under docs/plans/tui-lazygit-polish/golden-path/.
func TestGoldenPathProofFrames(t *testing.T) {
	outDir := filepath.Join("..", "..", "docs", "plans", "tui-lazygit-polish", "golden-path")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatal(err)
	}
	write := func(name, content string) {
		t.Helper()
		path := filepath.Join(outDir, name)
		if err := os.WriteFile(path, []byte(ansi.Strip(content)+"\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	// Shot 1: Home dual pane
	wfDir := t.TempDir()
	for _, name := range []string{"golden-path", "feature"} {
		body := "[workflow]\nname = \"" + name + "\"\nversion = \"1\"\ndescription = \"" + name + " demo\"\n\n[[step]]\nid = \"seed\"\ntype = \"command\"\nrun = \"true\"\n"
		if err := os.WriteFile(filepath.Join(wfDir, name+".toml"), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	exec := runner.NewFakeExecutor(nil, runner.FakeOutcome{})
	mgr := engine.NewManager(exec, "")
	var root tea.Model = tui.New(context.Background(), mgr)
	root, _ = root.Update(tea.WindowSizeMsg{Width: 100, Height: 24})
	root, cmd := root.Update(selector.DiscoverCmd(wfDir)())
	if cmd != nil {
		if msg := cmd(); msg != nil {
			root, _ = root.Update(msg)
		}
	}
	home := ansi.Strip(root.View().Content)
	if !strings.Contains(home, "Workflows") {
		t.Fatalf("home proof missing Workflows:\n%s", home)
	}
	write("01-home.txt", root.View().Content)

	// Shots 2–6 from Monitor
	m := monitor.New("abcd1234ef")
	m, _ = m.Update(tea.WindowSizeMsg{Width: 100, Height: 28})
	m, _ = m.Update(monitor.EngineEventMsg{Event: engine.RunStarted{
		RunID: "abcd1234ef", Workflow: "golden-path",
		Steps: []string{"seed", "gate"},
	}})
	m, _ = m.Update(monitor.EngineEventMsg{Event: engine.StepStatus{
		RunID: "abcd1234ef", StepID: "seed", To: step.StatusRunning,
	}})
	spent := 0.02
	m, _ = m.Update(monitor.EngineEventMsg{Event: engine.StepStatus{
		RunID: "abcd1234ef", StepID: "seed", To: step.StatusRunning,
		Cost: &spent, Tokens: 1200,
	}})
	m, _ = m.Update(tea.KeyPressMsg{Code: tea.KeyTab})
	live := ansi.Strip(m.View())
	if !strings.Contains(live, "LIVE") && !strings.Contains(live, "seed") {
		t.Fatalf("monitor live proof missing identity:\n%s", live)
	}
	write("02-monitor-live.txt", m.View())

	content := "Golden-path review document."
	m, _ = m.Update(monitor.EngineEventMsg{Event: engine.ReviewRequest{
		RunID: "abcd1234ef", StepID: "gate", Choices: []string{"accept", "revise"},
		Documents: []domainreview.Document{{
			ID: "arch", Label: "Architecture", Source: "ARCHITECTURE.md", Format: "markdown",
			Content: content, SHA256: domainreview.Digest(content), LineCount: 1,
		}},
	}})
	// First-wait auto-focuses Gate; Esc blurs to Steps for the unfocused chrome shot.
	m, _ = m.Update(tea.KeyPressMsg{Code: tea.KeyEsc})
	blurred := ansi.Strip(m.View())
	if !strings.Contains(blurred, "GATE · needs input") {
		t.Fatalf("blurred gate proof missing chrome:\n%s", blurred)
	}
	write("03-gate-blurred.txt", m.View())

	for i := 0; i < 3; i++ {
		if strings.Contains(ansi.Strip(m.View()), "[GATE]") {
			break
		}
		m, _ = m.Update(tea.KeyPressMsg{Code: tea.KeyTab})
	}
	focused := ansi.Strip(m.View())
	if !strings.Contains(focused, "[GATE]") {
		t.Fatalf("focused gate proof missing [GATE]:\n%s", focused)
	}
	write("04-gate-focused.txt", m.View())

	m, _ = m.Update(tea.WindowSizeMsg{Width: 180, Height: 40})
	m, _ = m.Update(tea.KeyPressMsg{Code: tea.KeyEnter})
	wide := ansi.Strip(m.View())
	if !strings.Contains(wide, "[REVIEW]") || strings.Contains(wide, "› Steps") || strings.Contains(wide, "[STEPS]") {
		t.Fatalf("review wide proof missing chrome:\n%s", wide)
	}
	write("05-review-wide.txt", m.View())

	m, _ = m.Update(tea.KeyPressMsg{Code: tea.KeyEsc})
	m, _ = m.Update(tea.WindowSizeMsg{Width: 100, Height: 28})
	m, _ = m.Update(tea.KeyPressMsg{Code: tea.KeyTab})
	footer := ansi.Strip(m.View())
	if !strings.Contains(footer, "simple") {
		t.Fatalf("simple footer proof missing tag:\n%s", footer)
	}
	write("06-footer-simple.txt", m.View())

	readme := `# Golden-path artifacts

Operator script: [SCRIPT.md](SCRIPT.md)  
Deterministic workflow: [` + "`.agents/jig/golden-path.toml`" + `](../../../../.agents/jig/golden-path.toml)

Text frames regenerated by:

` + "```bash\n" + `go test ./internal/tui -run TestGoldenPathProofFrames -count=1
` + "```\n\n" + `| File | Shot |
|---|---|
| ` + "`01-home.txt`" + ` | Home dual pane |
| ` + "`02-monitor-live.txt`" + ` | Monitor LIVE / seed running |
| ` + "`03-gate-blurred.txt`" + ` | ` + "`GATE · needs input`" + ` |
| ` + "`04-gate-focused.txt`" + ` | ` + "`[GATE] · awaiting review`" + ` |
| ` + "`05-review-wide.txt`" + ` | Full-width focused Review workspace |
| ` + "`06-footer-simple.txt`" + ` | Footer ` + "`simple`" + ` tag |
`
	if err := os.WriteFile(filepath.Join(outDir, "README.md"), []byte(readme), 0o644); err != nil {
		t.Fatal(err)
	}
}
