package tui_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	tea "charm.land/bubbletea/v2"

	"jig/internal/engine"
	domainreview "jig/internal/review"
	"jig/internal/step"
	"jig/internal/tui/monitor"
)

func TestPhase2ProofFrames(t *testing.T) {
	dir := filepath.Join("..", "..", "docs", "plans", "tui-lazygit-polish", "phase-2", "proofs")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	write := func(name, content string) {
		t.Helper()
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(stripANSI(content)+"\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	m := monitor.New("abcd1234ef")
	m, _ = m.Update(tea.WindowSizeMsg{Width: 100, Height: 28})
	m, _ = m.Update(monitor.EngineEventMsg{Event: engine.RunStarted{
		RunID: "abcd1234ef", Workflow: "feature",
		Steps: []string{"plan", "implement", "review"},
	}})
	m, _ = m.Update(monitor.EngineEventMsg{Event: engine.StepStatus{
		RunID: "abcd1234ef", StepID: "implement", To: step.StatusRunning,
	}})
	spent := 0.08
	m, _ = m.Update(monitor.EngineEventMsg{Event: engine.StepStatus{
		RunID: "abcd1234ef", StepID: "plan", To: step.StatusSucceeded,
		Cost: &spent, Tokens: 12400,
	}})
	m, _ = m.Update(tea.KeyPressMsg{Code: tea.KeyTab}) // transcript focus
	write("2.2-slim-titles-transcript.txt", m.View())

	content := "Design notes for the golden path."
	m, _ = m.Update(monitor.EngineEventMsg{Event: engine.ReviewRequest{
		RunID: "abcd1234ef", StepID: "review", Choices: []string{"accept", "revise"},
		Documents: []domainreview.Document{{
			ID: "design", Label: "design.md", Source: "design.md", Format: "markdown",
			Content: content, SHA256: domainreview.Digest(content), LineCount: 1,
		}},
	}})
	for i := 0; i < 3; i++ {
		if strings.Contains(stripANSI(m.View()), "[GATE]") {
			break
		}
		m, _ = m.Update(tea.KeyPressMsg{Code: tea.KeyTab})
	}
	m, _ = m.Update(tea.WindowSizeMsg{Width: 180, Height: 40})
	m, _ = m.Update(tea.KeyPressMsg{Code: tea.KeyEnter})
	wide := stripANSI(m.View())
	if !strings.Contains(wide, "[REVIEW]") || strings.Contains(wide, "› Steps") || strings.Contains(wide, "[STEPS]") {
		t.Fatalf("wide focused-review proof has the wrong chrome:\n%s", wide)
	}
	write("2.1-review-embed-wide.txt", m.View())

	m, _ = m.Update(tea.WindowSizeMsg{Width: 120, Height: 40})
	narrow := stripANSI(m.View())
	if !strings.Contains(narrow, "[REVIEW]") {
		t.Fatalf("narrow review proof missing [REVIEW]:\n%s", narrow)
	}
	write("2.1-review-embed-narrow.txt", m.View())

	m, _ = m.Update(tea.KeyPressMsg{Code: tea.KeyEsc})
	m, _ = m.Update(tea.WindowSizeMsg{Width: 100, Height: 28})
	m, _ = m.Update(tea.KeyPressMsg{Code: tea.KeyTab})
	write("2.3-footer-simple.txt", m.View())
}

func TestPhase2ProofsREADME(t *testing.T) {
	dir := filepath.Join("..", "..", "docs", "plans", "tui-lazygit-polish", "phase-2", "proofs")
	readme := `# Phase 2 proofs

Text frames regenerated by:

` + "```bash\n" + `go test ./internal/tui -run TestPhase2ProofFrames -count=1
` + "```\n\n" + `| File | Item |
|---|---|
| ` + "`2.1-review-embed-wide.txt`" + ` | Full-width focused Review at 180 columns |
| ` + "`2.1-review-embed-narrow.txt`" + ` | Full-width focused Review at 120 columns |
| ` + "`2.2-slim-titles-transcript.txt`" + ` | Slim step · Transcript titles |
| ` + "`2.3-footer-simple.txt`" + ` | Footer ` + "`simple`" + ` tag |
`
	if err := os.WriteFile(filepath.Join(dir, "README.md"), []byte(readme), 0o644); err != nil {
		t.Fatal(err)
	}
}
