package monitor

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"jig/internal/toolcall"
	"jig/internal/transcript"
)

// TestDiffRenderGallery writes deterministic ANSI captures of the
// canonical slice-07 diff shapes and their Monitor-wired composition
// under JIG_UI_SNAPSHOT_DIR. It parallels TestTruncationSharedGallery
// so proof artifacts live beside their production helpers and are
// only generated when the reviewer explicitly asks for them.
func TestDiffRenderGallery(t *testing.T) {
	dir := os.Getenv("JIG_UI_SNAPSHOT_DIR")
	if dir == "" {
		t.Skip("set JIG_UI_SNAPSHOT_DIR to capture the diff-rendering gallery")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}

	sections := []struct {
		title    string
		path     string
		old, new string
	}{
		{"Single-line replacement", "greeting.go",
			"func Greet(name string) string { return \"hi, \" + name }\n",
			"func Greet(name string) string { return \"hello, \" + name }\n"},
		{"Multi-line replacement", "config.go",
			"port := 8080\nhost := \"localhost\"\ntls := false\n",
			"port := 8443\nhost := \"0.0.0.0\"\ntls := true\n"},
		{"Pure insertion", "handlers.go",
			"func ping() string { return \"pong\" }\n",
			"func ping() string { return \"pong\" }\n\nfunc health() string { return \"ok\" }\n"},
		{"Pure deletion", "prune.go",
			"a := 1\nb := 2\nc := 3\n",
			"a := 1\nc := 3\n"},
		{"Indented change (indent viz + intra-line)", "loops.go",
			"\tfor i := 0; i < 10; i++ {\n\t\tsum += items[i]\n\t}\n",
			"\tfor i := 0; i < 20; i++ {\n\t\tsum += items[i]\n\t}\n"},
	}

	var wideAnsi strings.Builder
	fmt.Fprintln(&wideAnsi, "# Slice 07 diff-rendering gallery — width 90")
	fmt.Fprintln(&wideAnsi, "#")
	fmt.Fprintln(&wideAnsi, "# Generated by TestDiffRenderGallery in")
	fmt.Fprintln(&wideAnsi, "# internal/tui/monitor/monitor_diff_gallery_test.go.")
	fmt.Fprintln(&wideAnsi, "# Command: JIG_UI_SNAPSHOT_DIR=<dir> go test ./internal/tui/monitor \\")
	fmt.Fprintln(&wideAnsi, "#           -run TestDiffRenderGallery -count=1")
	fmt.Fprintln(&wideAnsi)

	var narrowAnsi strings.Builder
	fmt.Fprintln(&narrowAnsi, "# Slice 07 diff-rendering gallery — width 60")
	fmt.Fprintln(&narrowAnsi)

	widths := []int{60, 90}
	builders := map[int]*strings.Builder{60: &narrowAnsi, 90: &wideAnsi}
	for _, width := range widths {
		b := builders[width]
		for _, tc := range sections {
			proj, stats, outcome := computeDiff(newDiff(tc.path, tc.old, tc.new))
			if outcome != computeOK {
				t.Fatalf("computeDiff outcome = %v for %s", outcome, tc.title)
			}
			fmt.Fprintf(b, "## %s (%s, +%d/-%d)\n", tc.title, tc.path, stats.added, stats.removed)
			fmt.Fprintln(b)
			rows := renderDiffRows(proj, tc.path, width, true, nil, "space")
			for _, row := range rows {
				b.WriteString(row + "\n")
			}
			fmt.Fprintln(b)
		}
		// Collapsed many-hunk sample.
		var oldB, newB strings.Builder
		for i := 0; i < 12; i++ {
			for j := 0; j < 20; j++ {
				line := fmt.Sprintf("shared-%d-%d\n", i, j)
				oldB.WriteString(line)
				newB.WriteString(line)
			}
			fmt.Fprintf(&oldB, "old-%d\n", i)
			fmt.Fprintf(&newB, "new-%d\n", i)
		}
		proj, _, outcome := computeDiff(newDiff("many.go", oldB.String(), newB.String()))
		if outcome != computeOK {
			t.Fatalf("collapsed sample failed to compute: %v", outcome)
		}
		fmt.Fprintf(b, "## Collapsed many-hunk sample (%d hunks total, budget %d/%d)\n",
			len(proj.Presentation.Hunks), diffCollapsedHunks, diffCollapsedLines)
		fmt.Fprintln(b)
		for _, row := range renderDiffRows(proj, "many.go", width, false, nil, "space") {
			b.WriteString(row + "\n")
		}
		fmt.Fprintln(b)
	}

	writeGallery := func(name string, b *strings.Builder) {
		out := filepath.Join(dir, name)
		if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}
	writeHTMLAndPNG := func(baseName, ansi string) {
		htmlPath := filepath.Join(dir, baseName+".html")
		if err := os.WriteFile(htmlPath, []byte(terminalHTML(ansi)), 0o644); err != nil {
			t.Fatalf("write %s: %v", htmlPath, err)
		}
		if _, err := exec.LookPath("google-chrome"); err != nil {
			return
		}
		pngPath := filepath.Join(dir, baseName+".png")
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		fileURL := "file://" + htmlPath
		args := []string{
			"--headless=new",
			"--no-sandbox",
			"--disable-gpu",
			"--hide-scrollbars",
			"--force-device-scale-factor=2",
			"--window-size=1280,720",
			"--screenshot=" + pngPath,
			fileURL,
		}
		out, err := exec.CommandContext(ctx, "google-chrome", args...).CombinedOutput()
		if err != nil {
			t.Logf("chrome screenshot %s failed: %v\n%s", baseName, err, out)
			return
		}
		t.Logf("wrote %s", pngPath)
	}
	writeGallery("25-task-2-diff-gallery-w60.txt", &narrowAnsi)
	writeGallery("25-task-2-diff-gallery-w90.txt", &wideAnsi)
	writeHTMLAndPNG("25-task-2-diff-gallery-w60", narrowAnsi.String())
	writeHTMLAndPNG("25-task-2-diff-gallery-w90", wideAnsi.String())

	// Monitor composition captures: adjacent expanded exchanges under
	// one transcript. Uses newMonitorWithSteps + setChatPage so the
	// output includes the header card, +N/-M badge, and Diff section.
	var monitor strings.Builder
	fmt.Fprintln(&monitor, "# Slice 07 Monitor diff composition — width 80")
	fmt.Fprintln(&monitor, "#")
	fmt.Fprintln(&monitor, "# Shows: (1) an edit whose diff renders, (2) a file-creation")
	fmt.Fprintln(&monitor, "# fallback, (3) a clamped-content warning above a diff, and")
	fmt.Fprintln(&monitor, "# (4) a collapsed many-hunk edit at 80 columns. Each row is")
	fmt.Fprintln(&monitor, "# already Charmtone-themed; the notes file records the exact")
	fmt.Fprintln(&monitor, "# terminal geometry and expand key.")
	fmt.Fprintln(&monitor)
	m := newMonitorWithSteps(t)
	entries := monitorGalleryEntries()
	m.setChatPage(transcript.Page{Entries: entries})
	monitor.WriteString(m.itemTranscriptBody())
	writeGallery("25-task-3-monitor-diff.txt", &monitor)
	writeHTMLAndPNG("25-task-3-monitor-diff", monitor.String())

	// Notes file records geometry so a reviewer can reproduce.
	notes := filepath.Join(dir, "25-task-2-diff-gallery.notes.txt")
	body := "Generated by TestDiffRenderGallery in internal/tui/monitor/monitor_diff_gallery_test.go.\n" +
		"Command: JIG_UI_SNAPSHOT_DIR=<dir> go test ./internal/tui/monitor -run TestDiffRenderGallery -count=1\n" +
		"Widths: 60 and 90 (diff-gallery); 80 (monitor-diff).\n" +
		"Expand key: `space` (fixture matches the Toggle binding's Help().Key literal).\n" +
		"Sample paths: greeting.go, config.go, handlers.go, prune.go, loops.go, many.go.\n" +
		"Sources are fabricated fixtures; no real .jig/ content or credentials appear.\n"
	if err := os.WriteFile(notes, []byte(body), 0o644); err != nil {
		t.Fatalf("write gallery notes: %v", err)
	}
}

// monitorGalleryEntries builds a synthetic transcript page that
// exercises the four Monitor-visible slice-07 shapes: an edit whose
// diff renders, a file-creation fallback, a clamped-content warning,
// and a collapsed many-hunk edit. Every payload is fabricated so no
// real .jig/ data or credentials leak into the gallery.
func monitorGalleryEntries() []transcript.Entry {
	oldA := "func Greet(name string) string { return \"hi, \" + name }\n"
	newA := "func Greet(name string) string { return \"hello, \" + name }\n"
	oldC := "port := 8080\nhost := \"localhost\"\ntls := false\n"
	newC := "port := 8443\nhost := \"0.0.0.0\"\ntls := true\n"
	var oldD, newD strings.Builder
	for i := 0; i < 12; i++ {
		for j := 0; j < 20; j++ {
			line := fmt.Sprintf("shared-%d-%d\n", i, j)
			oldD.WriteString(line)
			newD.WriteString(line)
		}
		fmt.Fprintf(&oldD, "old-%d\n", i)
		fmt.Fprintf(&newD, "new-%d\n", i)
	}

	entries := []transcript.Entry{
		makeExchange("e1", "greeting.go", &oldA, newA, false, false),
		makeExchange("e2", "brand-new.go", nil, "package new\n", false, false),
		makeExchange("e3", "config.go", &oldC, newC, true, false),
		makeExchange("e4", "many.go", strPtr(oldD.String()), newD.String(), false, true),
	}
	flat := make([]transcript.Entry, 0, len(entries)*2)
	for i, group := range entries {
		group.Seq = i * 2
		flat = append(flat, group)
	}
	return append(flat, entries...)
}

// makeExchange fabricates a two-block edit exchange for the gallery.
// truncated forces the tool-use block's Truncated flag so the diff
// section prepends DiffClampedHint. `collapsed` renders the exchange
// in its default-collapsed state.
func makeExchange(id, path string, oldText *string, newText string, truncated, collapsed bool) transcript.Entry {
	_ = collapsed
	entry := transcript.Entry{
		Role: transcript.RoleAssistant,
		Blocks: []transcript.Block{
			{
				Type:      transcript.BlockToolUse,
				Truncated: truncated,
				Tool:      &toolcall.Activity{ID: id, Kind: "edit", Title: "Editing " + path},
			},
			{
				Type: transcript.BlockToolResult,
				Tool: &toolcall.Activity{
					ID: id, Kind: "edit", Status: "completed",
					Content: []toolcall.Content{{Diff: &toolcall.Diff{
						Path: path, OldText: oldText, NewText: newText,
					}}},
				},
			},
		},
	}
	return entry
}

func strPtr(s string) *string { return &s }
