name: ci

on:
  push:
    branches: [main]
  pull_request: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: go build
        run: go build ./cmd/jig
      - name: go vet
        run: go vet ./...
      - name: go test
        run: go test ./...
      - name: gofmt
        run: |
          files=$(gofmt -l $(git ls-files '*.go'))
          if [ -n "$files" ]; then
            echo "$files"
            exit 1
          fi
